!==============================================================================
!   CGEM
!   Info
!   Copyright
!   License
!==============================================================================
subroutine cgem_run(istep,myrank)
  use schism_glbl, only : rkind,nea,idry_e,irange_tr,flx_sf,flx_bt,bdy_frc,&
   & nvrt,kbe,dpe,tr_el,dt,srad,elnode,i34,windx,windy,area,ze,wsett !,xlon_el,ylat_el
  use cgem, only: ws,skipcgem,checkwindrad,sinkwcgem,nf,debug,Which_rad,Which_wind,PARfac
  use grid, only: iYrS,START_SECONDS,km

  implicit none

  integer, intent(in) :: istep,myrank
  integer :: itmp1,itmp2,i,m,im,mm,k
  integer :: TC_8
  logical :: dowrite
  real :: x
  real(rkind) :: ff(nf),ff_new(nf),ff_in(km,nf),ff_out(km,nf),dz(km),PAR(km)
  real(rkind) :: fs_in(km),fs_out(km)
  real(rkind) :: Rad, Wind, T, S, d_sfc
  real(rkind) :: lat,lon
  real(rkind), parameter :: cv        = 2.77e14 ! multiplicative factor used
                                             ! to convert from watts/m2 
                                             ! to photons/cm2/sec
                                             ! Morel and Smith (1974)
  external :: cgem_step !, cgem_flux, cgem_sink
  
  !Just say Hi in mirror.out
  if(myrank==0) write(16,*) "In cgem_run: istep,dt=",istep,dt
  !Time in seconds since start of run
  TC_8 = START_SECONDS + istep*int(dt)
  lat = 36.d0
  lon = 86.d0
!Range of tracers, first 2 are S,T, then CGEM are next
  itmp1=irange_tr(1,3)
  itmp2=irange_tr(2,3)

!Loop over elements
  do i=1,nea

  !Skip if element is dry
    if(idry_e(i)==1) cycle

  !If not dry, run CGEM

    !Set surface and bottom flux, and body forces to zero
    flx_sf(itmp1:itmp2,i)=0.d0
    flx_bt(itmp1:itmp2,i)=0.d0
    bdy_frc(itmp1:itmp2,:,i)=0.d0

  if(Which_rad.eq.1) then
    !Wind/Rad expressions copied directly from cosine.F90
    !Convert Rad from W/m2 to photons/cm2/sec
    Rad = max(sum(srad(elnode(1:i34(i),i)))/i34(i),0.d0)*cv
  else
    call getSolar( iYrS, TC_8, lon, lat, Rad)
    ! Rad is just above sea surface.
  ! Rad was short wave generated by NRL, multiplied by SWtoPAR: ratio of PAR to
  ! shortwave radiation (hardcoded 4/30/14 to 0.43).
  ! Hardcoded to 0.47 on 2/11/16, Re: Tsubo and Walker, 2005
  ! PARfac is a multiplication factor for testing
    Rad = (0.47*Rad) * PARfac
  endif

  if(Which_wind.eq.1) then
    !Wind/Rad expressions copied directly from cosine.F90
    Wind=sqrt((sum(windx(elnode(1:i34(i),i)))/real(i34(i),rkind))**2.0+(sum(windy(elnode(1:i34(i),i)))/real(i34(i),rkind))**2.0)
  else
    Wind = 5.d0 
  endif


  !This will write Wind/Rad for every single timestep, don't run for long or
  !the resulting text file will be enormous.
  if(myrank.eq.1.and.i.eq.1.and.checkwindrad.eq.1) write(16,*) "Wind,Rad,Minutes",Wind,Rad/cv,istep,istep*int(dt)/60./60.

  dowrite=.FALSE.
  if(i.eq.10.and.myrank.eq.1) dowrite=.TRUE.

  !The option to skip cgem is for verifying initial and boundary conditions,
!  sinking, and loading without cgem complicating the process 
if(skipcgem.eq.1) then
  !Don't call cgem
else
  !Call CGEM for a cell
  !Input is ff, output is ff_new
  !call cgem_step(TC_8,cgemdt,istep,i,myrank)
  !Call the light model
     im = 0 
     do k=nvrt,kbe(i)+1,-1
        im = im+1
        ff_in(im,1:nf) = tr_el(itmp1:itmp2,k,i)
        dz(im) = ze(k,i)-ze(k-1,i)
     enddo !k

  call call_iop_par(ff_in,im,TC_8,Rad,dz,lat,lon,PAR)
  if(i.eq.10.and.debug.eq.1) write(6,*) "PAR",PAR
  if(i.eq.10.and.debug.eq.1) write(6,*) "dz",dz
  if(i.eq.10.and.debug.eq.1) write(6,*) "tot_dz",SUM(dz(1:im))
  !Update schism tracer variables with newly calculated cgem variables
   im = 0 
   do k=nvrt,kbe(i)+1,-1
      im = im + 1
      T = tr_el(1,k,i)
      S = tr_el(2,k,i)
      ff(1:nf) = tr_el(itmp1:itmp2,k,i)
      d_sfc = -1.*(ze(k-1,i)-ze(nvrt,i))
      if(i.eq.10.and.k.eq.nvrt.and.debug.eq.1) write(6,*) "istep=",istep
      if(i.eq.10.and.k.eq.nvrt.and.debug.eq.1) write(6,*) i,k,nvrt,d_sfc,T,S,Rad,dt
      call cgem_step(ff,ff_new,dT, S, T, PAR(im), Wind, lat, d_sfc, .FALSE., .TRUE.)
      tr_el(itmp1:itmp2,k,i) = ff_new(1:nf)
      if(i.eq.10.and.k.eq.nvrt.and.debug.eq.1) write(6,*) "tr",tr_el(itmp1:itmp2,k,i)
      if(i.eq.10.and.debug.eq.1) write(6,*) "d_sfc",d_sfc
   enddo !k
endif !end sink cgem

    if(sinkwcgem) then
      do m=itmp1,itmp2
         mm=m+2
         if(ws(mm).gt.tiny(x)) then
           fs_in(:) = tr_el(m,:,i)
           call cgem_sink(fs_in,fs_out,im,dz,dt,i,istep,myrank)
           tr_el(m,:,i) = fs_out(:)
         endif
      enddo !k
      if(i.eq.10.and.k.eq.nvrt.and.debug.eq.1) write(6,*) "tr",tr_el(itmp1:itmp2,k,i)
      do m=itmp1,itmp2
       wsett(m,:,i) = 0.d0
      enddo
    else
    !--Since this is constant, I'd rather define it somewhere else, but
    !- it was not registering properly.  I'll get back to this.
    !wsett is settling velocity
    mm = 1                 !cgem tracers are mm=1:nf
      do m=itmp1,itmp2       !schism's are m=itmp1:itmp2
        wsett(m,:,i)= ws(mm) !ws(nf) is cgem sinking array
        mm = mm+1
      enddo
    endif

  enddo !inea

return
end subroutine cgem_run
